<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/arrayIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
arr=np.arange(11,41).reshape(6,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [12]:
brr=np.arange(11,31)
brr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

**Array Slicing**

In [13]:
brr[5:10]

array([16, 17, 18, 19, 20])

In [14]:
arr[1]   # row 1 print krdi

array([16, 17, 18, 19, 20])

In [16]:
arr[1:3]  # row 1 and 2 print krdi..

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr[1:3,1:3]  #slicing....

array([[17, 18],
       [22, 23]])

In [18]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [19]:
#column 3 print...
arr[:,3]

array([14, 19, 24, 29, 34, 39])

In [22]:
#11 15 31 35
arr[0:5:4,::4]

array([[11, 15],
       [31, 35]])

**Boolean Indexing**

In [23]:
#print even numbers only

In [34]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [36]:
arr[arr%2==0]  #only true values print

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])