<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/arrayOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [9]:
b=np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [10]:
a+b   # broadcasting ho ri on numpy array..

array([ 7,  9, 11, 13, 15])

In [11]:
a*b

array([ 6, 14, 24, 36, 50])

In [12]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
a//b

array([0, 0, 0, 0, 0])

In [14]:
a*2

array([ 2,  4,  6,  8, 10])

In [20]:
arr*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
#List pe broadcasting nhi ho skti
l=[1,2,3]
# l+2           error
l=np.array(l)
l+2


array([3, 4, 5])

**Deep and Shallow Copy**

In [26]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [27]:
b=a

In [28]:
b[0]=10

In [30]:
b

array([10,  2,  3,  4,  5])

In [31]:
a

array([10,  2,  3,  4,  5])

In [ ]:
# a too changes --->known as deep copy (same Address point krne lg jata) ....to Avoid this Use Shallow Copy

In [38]:
a=np.arange(1,6)
c=a.copy()           #Shallow copy different address pe banti c ki array

In [39]:
c[0]=10

In [40]:
c

array([10,  2,  3,  4,  5])

In [41]:
a

array([1, 2, 3, 4, 5])

**Matrix Operations**

In [43]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
c=np.dot(a,b)
c

array([[30, 36, 42],
       [66, 81, 96]])

In [55]:
a @ b  #for dot product too...

array([[30, 36, 42],
       [66, 81, 96]])

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Advance Array Manipulation-> Stack and Splitting**

In [58]:
# hstack and vstack  mtlb jodnaaaa....

In [59]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [66]:
b=np.arange(7,12)
b

array([ 7,  8,  9, 10, 11])

In [67]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [68]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [69]:
np.column_stack((a,b))   #column wise jodnaaaa...

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [70]:
#Splitting

In [77]:
a=np.arange(1,37).reshape(6,6)

In [78]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [79]:
np.hsplit(a,3)   # 3 parts me split kr rhe

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [80]:
np.vsplit(a,2)   # 2 parts me split kr rhe...

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]