<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy->Same data type only unlike list**







In [1]:
import numpy as np

**Array Creation**

In [4]:
arr=np.array([1,2,3])  #same data type aagr alag dala to bda wlaa le legaa...
arr

array([1, 2, 3])

In [5]:
arr=np.array([1,2,3,"HEllo"])   # in string...
arr

array(['1', '2', '3', 'HEllo'], dtype='<U21')

In [7]:
# in list the 2d array is not created see-->
arr=[[1,2,3],
     [4,5,6],
     [7,8,9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(arr)   #2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Some array generation functions**

In [14]:
arr=np.arange(0,12,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [19]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr=np.linspace(0,9,10)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

**Random Generation Functions**

In [30]:
arr=np.random.rand(10)   #10 numbers between 0 and 1(normalization)
arr

array([0.38501566, 0.96087961, 0.05694506, 0.84212005, 0.73138404,
       0.52921589, 0.5850954 , 0.08258546, 0.27619947, 0.89864033])

In [31]:
arr=np.random.randn(10)   # numbers between -3 and 3 (standardization)
arr

array([-1.17244587,  0.29143398,  0.7187458 ,  1.57556896, -0.8467758 ,
        0.92552125,  0.34527175,  0.10126253, -1.20108734,  1.56429844])

In [34]:
arr=np.random.randint(10,20,10)  #10 numbers generate krega between 10 and 20
arr

array([15, 14, 10, 17, 13, 15, 14, 14, 10, 14])

**Array attributes**

In [72]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr.shape

(3, 3)

In [74]:
arr.size

9

In [75]:
arr.dtype

dtype('int64')

**Array functions**

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.min(arr)

np.int64(1)

In [78]:
np.max(arr)

np.int64(9)

In [79]:
np.sum(arr)

np.int64(45)

In [80]:
np.mean(arr)

np.float64(5.0)

In [81]:
np.std(arr)

np.float64(2.581988897471611)

In [82]:
np.argmax(arr)   #index of the max element

np.int64(8)

In [83]:
np.argmin(arr)   #index of the min element

np.int64(0)

**Reshaping and Resizing**

In [87]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [90]:
arr=arr.reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])