<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/NumpyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Valid Suduko**

In [70]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [71]:
valid=True
if (np.sum(s,axis=1)!=45).any():     #axis use kiya to ek poora array dega na true false ka to
  print("Not a Valid suduko")        #any us poore array pe check krega ki any value !=45
if(np.sum(s,axis=0)!=45).any():
  print("Not a Valid suduko")


In [72]:
# ab 3X3 mein check kregeee

In [73]:
s[0:3,0:3]    # ese hi sab ka sum 45 hona chahiyee

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [74]:
for i in range(0,9,3):
  for j in range(0,9,3):
    if((np.sum(s[i:i+3,j:j+3]))!=45):     #ye ek value dega to siddha check (no any used or all)
      print("Not a valid suduko")
      valid=False
      break;
if(valid):
  print("Valid")

Valid


**General Questions**

In [137]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [138]:
#Get the shape of the matrix.
#Find the average age of students.
#Extract Math marks of all students.
#Find the highest Science mark.
#Get details of the student who scored more than 90 in Math.
#Increase Math marks of all students by 5.
#Find how many students are younger than 19.
#Calculate the average marks in each subject (column-wise mean).
#Get data of students who scored at least 80 in both subjects.
#Replace all Science marks < 75 with 0.

In [139]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [140]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [141]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [142]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [143]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [144]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [145]:
data[:,1]=data[:,1]+5

In [146]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [147]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [148]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [149]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [150]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]   #imp

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [152]:
data[:,2][data[:,2]<75]=0   #imp

In [153]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])